title: Jingqian's Data Visualization Projects
description: This repository showcases various data analysis projects completed using Google Looker Studio and Power BI. Each project includes a PDF version of the analysis report and provides a link to the corresponding report or dashboard. Nevertheless, accessing the original Power BI dashboard necessitates authorization. Kindly reach out to me if you intend to engage with the dashboard.
theme: jekyll-theme-cayman
